### ISSUE TITLE
Design and Implement Home Page for Refuge App

### ISSUE THREAD

**Issue by Sulton88Mehron90** [Refugee-Aid-Capstone/refugee-aid-fe#18]
# Design and Implement Home Page for Refuge App

As part of our ongoing efforts to improve the user experience on the Refuge app, we need to create a new homepage. The following are the specific requirements:

## Navbar:

- Located at the top of the page.
- On the right side, it should display the logo of the Refuge app.
- It should contain links to:
  - Aid
  - Donate
  - Organisation
  - [Possibly other links. Need to discuss]

### Image and Mission Statement:

- An image should be displayed on the left side of the page.
- On the right side, there should be a section titled "Our Mission" which will contain the mission statement or related content.

### Video Button:

- Below the image, there should be a button labeled "Play Video".
- Upon clicking this button:
  - The image should be hidden.
  - A video player should appear in its place.
  - The button's text should change to "Hide Video".
- Upon clicking the "Hide Video" button:
  - The video player should be hidden.
  - The image should reappear in its place.

## Important Notes:

- The "Our Mission" section should always remain visible on the page regardless of the state of the video player or image.
- Need to ensure the design is responsive and works well on both desktop and mobile devices.

## Tasks:

- [x] Finalize the design mockups considering the above requirements.
- [x] Implement the Navbar with all the required links.
- [x] Add the image and "Our Mission" section to the body.
- [x] Implement the video play/hide functionality.
- [x] Ensure responsiveness on various devices.
- [x] Review and finalize.
